name: crossvault_macos
description: macOS implementation of crossvault plugin using Keychain with iCloud sync support. Provides hardware-backed security via Secure Enclave.
version: 1.0.0
homepage: https://github.com/alex-melnyk/crossvault
repository: https://github.com/alex-melnyk/crossvault/tree/main/crossvault_macos
issue_tracker: https://github.com/alex-melnyk/crossvault/issues

topics:
  - macos
  - keychain
  - security
  - icloud
  - secure-enclave

environment:
  sdk: ^3.6.0
  flutter: '>=3.3.0'

flutter:
  plugin:
    implements: crossvault
    platforms:
      macos:
        pluginClass: CrossvaultMacosPlugin
        dartPluginClass: CrossvaultMacos

dependencies:
  flutter:
    sdk: flutter
  crossvault_platform_interface: ^1.0.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0
