name: crossvault_ios
description: iOS implementation of crossvault plugin using Keychain with iCloud sync support. Provides hardware-backed security via Secure Enclave.
version: 1.0.0
homepage: https://github.com/alex-melnyk/crossvault
repository: https://github.com/alex-melnyk/crossvault/tree/main/crossvault_ios
issue_tracker: https://github.com/alex-melnyk/crossvault/issues

topics:
  - ios
  - keychain
  - security
  - icloud
  - secure-enclave

environment:
  sdk: ^3.9.2
  flutter: '>=3.3.0'

flutter:
  plugin:
    implements: crossvault
    platforms:
      ios:
        pluginClass: CrossvaultIosPlugin
        dartPluginClass: CrossvaultIos

dependencies:
  flutter:
    sdk: flutter
  crossvault_platform_interface: ^1.0.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0
