name: crossvault_android
description: Android implementation of crossvault plugin using EncryptedSharedPreferences and Android Keystore with Auto Backup support.
version: 1.0.0
homepage: https://github.com/alex-melnyk/crossvault
repository: https://github.com/alex-melnyk/crossvault/tree/main/crossvault_android
issue_tracker: https://github.com/alex-melnyk/crossvault/issues

topics:
  - android
  - keystore
  - security
  - encryption
  - backup

environment:
  sdk: ^3.6.0
  flutter: '>=3.3.0'

flutter:
  plugin:
    implements: crossvault
    platforms:
      android:
        package: io.alexmelnyk.crossvault_android
        pluginClass: CrossvaultAndroidPlugin
        dartPluginClass: CrossvaultAndroid

dependencies:
  flutter:
    sdk: flutter
  crossvault_platform_interface: ^1.0.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0
